language: c

sudo: false

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
  - os: linux
    compiler: clang
    env: 
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - STATIC=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
  - os: linux
    compiler: clang
    env: STATIC=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - os: osx
    compiler: clang
    env: 
  - os: osx
    compiler: clang
    env: STATIC=1
  - os: osx
    compiler: clang
    env: NOTHREADS=1
  - os: osx
    compiler: clang
    env:
      - STATIC=1
      - NOTHREADS=1
  - os: linux
    compiler: gcc
    env: DIST=1
    dist: trusty
    sudo: true
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y pandoc
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - POLL=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - NOTHREADS=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - CENSUS=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - VALGRIND=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - valgrind
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - STATIC=1
      - VALGRIND=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - valgrind
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - NOTHREADS=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - VALGRIND=1 
      - NOTHREADS=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - valgrind
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - POLL=1
      - NOTHREADS=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - STATIC=1
      - NOTHREADS=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7" 
      - ARCH_FALLBACK=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
  - os: linux
    compiler: clang
    env: ARCH_FALLBACK=1 
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7"
      - THREAD_FALLBACK=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7

#
# Travis has old version of OpenSSL. Find out how to install version 1.1.0.
#
# - os: linux
#    compiler: gcc
#    env: TLS=1
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#        packages:
#          - gcc-7
#  - os: osx
#    compiler: clang
#    env: TLS=1
#    before_install: brew install openssl
#

branches:
  except:
    - gh-pages

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - ./autogen.sh
  - ./configure ${STATIC+--disable-shared} ${DEBUG+--enable-debug} ${VALGRIND+--enable-valgrind} ${CENSUS+--enable-census} ${TLS+--enable-tls} ${NOTHREADS+--disable-threads} CFLAGS="-O3 ${POLL+-DDILL_POLL} ${ARCH_FALLBACK+-DDILL_ARCH_FALLBACK} ${THREAD_FALLBACK+-DDILL_THREAD_FALLBACK} -DDILL_SLOW_TESTS"
  - make V=1 ${DIST+dist}

script:
  - test ${DIST+x} || make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
